# Generated by Django 6.0.6 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("Clear", "Clear"),
                            ("Rainy", "Rainy"),
                            ("Foggy", "Foggy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day_of_week", models.CharField(max_length=20)),
                ("time_of_day", models.CharField(max_length=20)),
                ("train_type", models.CharField(max_length=20)),
                ("historical_delay", models.IntegerField()),
                (
                    "route_congestion",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("predicted_delay", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
